robot_opts: -vv
clean: False
working_directory: /work
curie_map:
  RO: http://purl.obolibrary.org/obo/RO_
  HP: http://purl.obolibrary.org/obo/HP_
  BFO: http://purl.obolibrary.org/obo/BFO_
  UPHENO: http://purl.obolibrary.org/obo/UPHENO_
  oio: http://www.geneontology.org/formats/oboInOwl#
  IAO: http://purl.obolibrary.org/obo/IAO_
  dce: http://purl.org/dc/elements/1.1/
global:
  chains: []
  relations: []
  annotations:
    - id: rdfs:label
    - id: skos:exactMatch
    - id: oio:hasExactSynonym
    - id: IAO:0000115
ontologies:
  - id: hp
    sources: 
      - http://purl.obolibrary.org/obo/hp.owl
    roots:
      - id: HP:0000118
        biolink: biolink:PhenotypicFeature
    relations:
      - id: UPHENO:0000001
        biolink: biolink:DiseaseOrPhenotypicFeatureAssociationToThingAssociation
        materialize: true
        chains:
          - BFO:0000051|RO:0000052
      - id: BFO:0000051
        materialize: true
  - id: mondo
    sources: 
      - http://purl.obolibrary.org/obo/mondo.owl
  - id: go
    sources: 
      - http://purl.obolibrary.org/obo/go/go-plus.owl